version: "3.6"
services:
    organizr:
        container_name: organizr
        hostname: organizr
        image: organizr/organizr:latest
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - orgnazir:/config
        environment:
            - PUID=1
            - PGID=1
            - TZ=Europe/Luxembourg
