version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    deploy:
      replicas: 1
    container_name: uptime-kuma
    volumes:
      - uptime-kuma:/app/data
    ports:
      - "3001:3001"  # <Host Port>:<Container Port>
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default

volumes:
  uptime-kuma:

networks:
  nginx-proxy-manager_default:
    external: true
