---
- name: Update and Upgrade Ubuntu Servers
  hosts: server
  become: yes

  tasks:
    - name: Update APT Cache
      apt:
        update_cache: yes
      register: apt_update

    - name: Perform APT Upgrade
      apt:
        upgrade: safe
      when: apt_update.changed

    - name: Perform APT Autoremove
      apt:
        autoremove: yes
      when: apt_update.changed

    - name: Perform APT Autoclean
      apt:
        autoclean: yes
      when: apt_update.changed

    - name: Check if System Reboot is Required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Send Discord message
      uri:
        url: "https://discord.com/api/webhooks/1164117309955248219/swkj3BLJNSETIn_negQcaBMrJnPUdw_BqOMuykzrzB2TMrGzRUTdxmt478Y2JcJfs3lu"
        method: POST
        body_format: json
        body: '{"content": "Reboot required on {{ inventory_hostname }}"}'
        headers:
          Content-Type: application/json
        status_code: 204
      when: reboot_required.stat.exists

    - name: Reboot the server if required
      reboot:
      when: reboot_required.stat.exists

    - name: Wait for SSH to become available
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 49222
        state: started
        timeout: 120  # Adjust the timeout as needed
      register: ssh_result
      ignore_errors: yes

    - name: Send Discord message on successful reboot
      uri:
        url: "https://discord.com/api/webhooks/1164117309955248219/swkj3BLJNSETIn_negQcaBMrJnPUdw_BqOMuykzrzB2TMrGzRUTdxmt478Y2JcJfs3lu"
        method: POST
        body_format: json
        body: '{"content": "Server {{ inventory_hostname }} has successfully rebooted."}'
        headers:
          Content-Type: application/json
        status_code: 204
      when: not reboot_required.stat.exists  # Skip the task when no reboot is required
