version: '3.7'

networks:
  frontend:
    external: true
  backend:
    external: true

services:
  traefik:
    image: traefik:2.10.4
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
    environment:
      - CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
    networks:
      - frontend
      - backend
    deploy:
      replicas: 2  # Adjust the number of replicas as needed for high availability
      placement:
        constraints:
          - node.role == manager
